"""portfolio market field

Revision ID: 94af4d98dbc1
Revises: e538261dd9a3
Create Date: 2026-04-27 23:13:35.659243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94af4d98dbc1'
down_revision: Union[str, Sequence[str], None] = 'e538261dd9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('market', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'market')
    # ### end Alembic commands ###
